### ISSUE TITLE
Global Urban Climate Explorer: design an interface between global climate data and a state-of-the-art urban climate model

### ISSUE THREAD

**Issue by sunt05** [OpenDataHack2018/OpenDataHack2018-Brainstorming#18]
**Problem** 
How to seamlessly use climate data to examine urban climate globally across different time periods?

**Proposed solution** 
Design an interface to streamline the climate data retrieval and urban climate simulations and then derive a number of urban climate indices for exploration.

**Data (what data do you need? what format?)**
1. incoming solar radiation
1. incoming longwave radiation
2. near-surface air temperature
3. near-surface air humidity
4. near-surface air pressure
5. near-surface wind speed
6. precipitation

**Team**
- Ting Sun: urban climate modeller
- Zhenkun Li: engineer & software developer

**Comment by OpenDataHack2018** [comment]
Closing this issue as the team decided to withdraw
